{% set python_min = "3.11" %}
{% set name = "chemprop" %}
{% set version = "2.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/chemprop-{{ version }}.tar.gz
  sha256: 46f54eb1b5743d8b9512e6e8319fa956e88bc5534b7056326996e6527517ef34

build:
  noarch: python
  entry_points:
    - chemprop=chemprop.cli.main:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - descriptastorus
    - rich
    - pytorch >=2.1
    - python >={{ python_min }},<3.13
    - pytorch::pytorch >=2.1
    - astartes
    - aimsim
    - configargparse
    - lightning >=2.0
    - numpy <2.0.0
    - pandas
    - rdkit
    - scikit-learn
    - scipy

test:
  imports:
    - chemprop
  commands:
    - chemprop train --help
    - chemprop predict --help
    - chemprop hpopt --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/chemprop/chemprop
  summary: Molecular Property Prediction with Message Passing Neural Networks
  dev_url: https://github.com/chemprop/chemprop
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - JacksonBurns
    - jan-janssen
